// People with titles (require a company)
const titledPeople = [
  "The CEO of",
  "The CFO of",
  "The COO of",
  "The CTO of",
  "The CMO of",
  "The Founder of",
  "The Co-Founder of",
  "The Chairman of",
  "The Managing Director of",
  "A Corporate Executive at",
  "A Board Member of",
  "The Head of Marketing at",
  "The Head of Sales at",
  "The Head of Operations at",
  "The Chief Technology Officer of",
  "The Chief Financial Officer of",
  "The Chief Operating Officer of",
  "The Chief Marketing Officer of",
  "The Chief Human Resources Officer of",
  "The Chief Information Officer of",
  "The Chief Strategy Officer of",
  "The Chief Innovation Officer of",
  "The Chief Data Officer of",
];

// Full name people
const namedPeople = [
  // Original celebrities
  "Brad Pitt",
  "Taylor Swift",
  "Elon Musk",
  "Oprah Winfrey",
  "Tom Hanks",
  "Beyoncé",
  "Leonardo DiCaprio",
  "Dwayne Johnson",
  "Jennifer Lawrence",
  "Chris Hemsworth",
  "Scarlett Johansson",
  "Robert Downey Jr.",
  "Emma Watson",
  "Ryan Reynolds",
  "Margot Robbie",
  "Tim Cook",
  "Jeff Bezos",
  "Mark Zuckerberg",
  "Bill Gates",
  "Warren Buffett",
  // Tech Leaders & Billionaires
  "Sam Altman",
  "Satya Nadella",
  "Sundar Pichai",
  "Andy Jassy",
  "Jensen Huang",
  "Bernard Arnault",
  "Larry Ellison",
  "Steve Ballmer",
  "Reed Hastings",
  "Brian Chesky",
  "Daniel Ek",
  "Evan Spiegel",
  "Jack Dorsey",
  "Adam Neumann",
  "Sam Bankman-Fried",
  "Elizabeth Holmes",
  "Charlie Javice",
  "Trevor Milton",
  "Larry Page",
  "Sergey Brin",
  "Reid Hoffman",
  "Peter Thiel",
  "Marc Andreessen",
  "Ben Horowitz",
  "Travis Kalanick",
  "Garrett Camp",
  "Drew Houston",
  "Arash Ferdowsi",
  "Patrick Collison",
  "John Collison",
  "Alexis Ohanian",
  "Steve Huffman",
  "Kevin Systrom",
  "Mike Krieger",
  "Jan Koum",
  "Brian Acton",
  "David Baszucki",
  "Stewart Butterfield",
  "Cal Henderson",
  "Tobias Lütke",
  "Martin Lorentzon",
  "Chad Hurley",
  "Steve Chen",
  "Jawed Karim",
  "Nathan Blecharczyk",
  "Joe Gebbia",
  "Dustin Moskovitz",
  "Chris Hughes",
  "Eduardo Saverin",
  "Sean Parker",
  "Dara Khosrowshahi",
  "Tony Xu",
  "Logan Green",
  "John Zimmer",
  "Sean Rad",
  "Justin Mateen",
  "Bobby Murphy",
  "Evan Spiegel",
  "Daniel Ek",
  "Martin Lorentzon",
  "David Baszucki",
  "Erik Cassel",
  "David Karp",
  "Nat Friedman",
  "Daniel Gross",
  "Tobias Lütke",
  "Harley Finkelstein",
  "Tobi Lütke",
  "Emil Michael",
  "Ryan Graves",
  "Rachel Whetstone",
  "David Plouffe",
  "Jill Hazelbaker",
  "Travis VanderZanden",
  "Jonathan DiSimone",
  "Oscar Salazar",
  "Conrad Whelan",
  "Kevin Hartz",
  "Julia Hartz",
  "Andrew McCollum",
  "Joe Munoz",
  "Josh Mohrer",
  "Andy Fang",
  "Stanley Tang",
  "Evan Moore",
  "Jonathan Badeen",
  "Justin Mateen",
  "Sean Rad",
  "Bobby Murphy",
  "Evan Spiegel",
  "Niklas Zennström",
  "Janus Friis",
  "Lara Khosrowshahi",
  "Emmett Shear",
  "Mira Murati",
  "Ilya Sutskever",
  "Greg Brockman",
  "Wojciech Zaremba",
  "François Pinault",
  "François-Henri Pinault",
  "Amancio Ortega",
  "Carlos Slim",
  "Mukesh Ambani",
  "Gautam Adani",
  "Zhang Yiming",
  "Colin Huang",
  "Eric Yuan",
  "Frank Wang",
  "Ren Zhengfei",
  "Robin Li",
  "William Ding",
  "Pony Ma",
  "Masayoshi Son",
  "Hiroshi Mikitani",
  "Yusaku Maezawa",
  "Daniel Zhang",
  "Jack Ma",
  "Joe Tsai",
  "Michael Dell",
  "Michael Bloomberg",
  "David Koch",
  "Charles Koch",
  "Jim Walton",
  "Alice Walton",
  "Rob Walton",
  "Francois Pinault",
  "Gerard Arnault",
  "Antoine Arnault",
  "Alexandre Arnault",
  "Frédéric Arnault",
  "Jean Arnault",
  // Spotify Top Artists
  "Bad Bunny",
  "The Weeknd",
  "Drake",
  "Billie Eilish",
  "Kendrick Lamar",
  "Bruno Mars",
  "Ariana Grande",
  "Arijit Singh",
  "Fuerza Regida",
  "SZA",
  "Ed Sheeran",
  "Post Malone",
  "Travis Scott",
  "Justin Bieber",
  "Rihanna",
  "Eminem",
  "David Guetta",
  "Coldplay",
  "Lady Gaga",
  "Mariah Carey",
  "Sabrina Carpenter",
  "Lana Del Rey",
  "Harry Styles",
  "Olivia Rodrigo",
  "The Kid LAROI",
  "Doja Cat",
  "Dua Lipa",
  "Imagine Dragons",
  "OneRepublic",
  "Maroon 5",
  "BTS",
  "Blackpink",
  "J Balvin",
  "Maluma",
  "Shakira",
  "Karol G",
  "Anitta",
  "Rosalía",
  "Ozuna",
  "Daddy Yankee",
  // Forbes 30 Under 30 Notable
  "Coco Gauff",
  "Mikey Madison",
  "Doechii",
  "Benson Boone",
  "Shaboozey",
  "Drew Afualo",
  "Jayson Tatum",
  "Bobbi Althoff",
  "Xandra Pohl",
  "Alex Warren",
  "Marissa Bode",
  // Top Sports Players
  "LeBron James",
  "Lionel Messi",
  "Cristiano Ronaldo",
  "Tom Brady",
  "Serena Williams",
  "Roger Federer",
  "Rafael Nadal",
  "Novak Djokovic",
  "Stephen Curry",
  "Kevin Durant",
  "Giannis Antetokounmpo",
  "Luka Dončić",
  "Patrick Mahomes",
  "Aaron Rodgers",
  "Travis Kelce",
  "Mike Trout",
  "Shohei Ohtani",
  "Max Verstappen",
  "Lewis Hamilton",
  "Tiger Woods",
  "Rory McIlroy",
  "Jon Rahm",
  "Kylian Mbappé",
  "Erling Haaland",
  "Virat Kohli",
  "Sachin Tendulkar",
  "Usain Bolt",
  "Simone Biles",
  "Katie Ledecky",
  "Michael Phelps",
  "Conor McGregor",
  "Jon Jones",
  "Canelo Álvarez",
  "Floyd Mayweather",
  "Manny Pacquiao",
];

const companies = [
  // Technology
  "Apple",
  "Google",
  "Microsoft",
  "Amazon",
  "Meta",
  "Netflix",
  "Tesla",
  "Spotify",
  "Twitter",
  "Uber",
  "Airbnb",
  "Samsung",
  "Sony",
  "IBM",
  "Intel",
  "Cisco",
  "Oracle",
  "HP",
  "Dell",
  "Lenovo",
  "LG",
  "Panasonic",
  "Nokia",
  "Huawei",
  "Xiaomi",
  "Alibaba",
  "Tencent",
  "Baidu",
  "JD.com",
  "Adobe",
  "Salesforce",
  "Zoom",
  "Palantir",
  "Nvidia",
  "AMD",
  // Finance
  "Goldman Sachs",
  "JPMorgan Chase",
  "Bank of America",
  "Wells Fargo",
  "Citigroup",
  "Morgan Stanley",
  "HSBC",
  "Deutsche Bank",
  "UBS",
  "Barclays",
  "BNP Paribas",
  "Visa",
  "Mastercard",
  "PayPal",
  "Square",
  "Stripe",
  "Berkshire Hathaway",
  // Consumer Goods
  "Coca-Cola",
  "PepsiCo",
  "Nestlé",
  "Unilever",
  "Procter & Gamble",
  "Johnson & Johnson",
  "Nike",
  "Adidas",
  "Starbucks",
  "McDonald's",
  "Walmart",
  "Target",
  "Costco",
  "Home Depot",
  "IKEA",
  // Entertainment
  "Disney",
  "Warner Bros.",
  "Universal Studios",
  "Paramount Pictures",
  "Sony Pictures",
  "a VC Firm",
];

// Government positions (require a country)
const politicians = [
  "The President of",
  "The Vice President of",
  "The Prime Minister of",
  "The Chancellor of",
  "The Governor of",
  "The Mayor of",
  "The Secretary of State of",
  "The Minister of Defense of",
  "The Minister of Finance of",
  "The Minister of Foreign Affairs of",
  "The Attorney General of",
  "The Chief Justice of",
  "The Speaker of the House of",
  "The Senate Majority Leader of",
  "The Senate Minority Leader of",
  "The House Majority Leader of",
  "The House Minority Leader of",
  "The Secretary of Defense of",
  "The Secretary of Treasury of",
  "The Secretary of Homeland Security of",
];

const countries = [
  "the United States",
  "China",
  "Russia",
  "India",
  "Brazil",
  "Japan",
  "Germany",
  "France",
  "United Kingdom",
  "Italy",
  "South Korea",
  "Canada",
  "Australia",
  "Mexico",
  "Spain",
  "Indonesia",
  "Saudi Arabia",
  "Turkey",
  "Argentina",
  "South Africa",
  "Egypt",
  "Poland",
  "Thailand",
  "Vietnam",
  "Pakistan",
  "Bangladesh",
  "Nigeria",
  "Philippines",
  "Iran",
  "Iraq",
  "Israel",
  "Palestine",
  "Ukraine",
  "North Korea",
  "Venezuela",
  "Cuba",
  "Syria",
  "Afghanistan",
  "Myanmar",
  "Belarus",
  "Zimbabwe",
  "Sudan",
  "Yemen",
  "Libya",
  "Somalia",
  "Eritrea",
  "Turkmenistan",
  "Uzbekistan",
  "Kazakhstan",
  "Azerbaijan",
  "Armenia",
  "Georgia",
  "Moldova",
  "Romania",
  "Bulgaria",
  "Greece",
  "Portugal",
  "Netherlands",
  "Belgium",
  "Switzerland",
  "Austria",
  "Sweden",
  "Norway",
  "Denmark",
  "Finland",
  "Ireland",
  "New Zealand",
  "Singapore",
  "Malaysia",
  "Taiwan",
  "Hong Kong",
  "Chile",
  "Peru",
  "Colombia",
  "Ecuador",
  "Bolivia",
  "Paraguay",
  "Uruguay",
  "Guatemala",
  "Honduras",
  "El Salvador",
  "Nicaragua",
  "Costa Rica",
  "Panama",
  "Jamaica",
  "Haiti",
  "Dominican Republic",
  "Trinidad and Tobago",
  "Kenya",
  "Ethiopia",
  "Tanzania",
  "Ghana",
  "Morocco",
  "Algeria",
  "Tunisia",
  "Lebanon",
  "Jordan",
  "Kuwait",
  "Qatar",
  "United Arab Emirates",
  "Oman",
  "Bahrain",
];

const actions = [
  "gets arrested for driving under the influence",
  "gets arrested for possession of a weapon",
  "gets arrested for possession of a controlled substance",
  "gets arrested for tax fraud",
  "gets arrested for money laundering",
  "gets arrested for insider trading",
  "gets arrested for embezzlement",
  "gets arrested for wire fraud",
  "gets arrested for securities fraud",
  "gets arrested for assault",
  "gets arrested for battery",
  "gets arrested for domestic violence",
  "gets arrested for public intoxication",
  "gets arrested for disorderly conduct",
  "gets arrested for resisting arrest",
  "gets arrested for obstruction of justice",
  "gets arrested for perjury",
  "gets arrested for bribery",
  "gets arrested for extortion",
  "gets arrested for racketeering",
  "appears on Epstein flight logs",
  "has a sex tape leaked",
  "has a deep sea submarine implosion",
  "dies in an orgy",
  "is caught with a prostitute",
  "dies in a private jet crash",
  "dies in a helicopter crash",
  "dies in a yacht accident",
  "dies in a skiing accident",
  "dies in a car crash",
  "dies from an overdose",
  "dies from a drug-related incident",
  "gets caught in a cheating scandal",
  "gets caught in an affair",
  "gets caught shoplifting",
  "gets caught with a prostitute",
  "gets caught soliciting prostitution",
  "gets caught in a human trafficking ring",
  "gets caught in a Ponzi scheme",
  "gets caught in a crypto scam",
  "gets caught in a pyramid scheme",
  "commits a hate crime",
  "gets caught committing securities fraud",
  "gets caught committing insurance fraud",
  "gets caught committing credit card fraud",
  "gets caught committing identity theft",
  "gets caught committing cybercrime",
  "gets caught committing child endangerment",
  "gets caught committing animal cruelty",
  "gets caught committing environmental crimes",
  "gets caught committing antitrust violations",
  "gets caught committing price fixing",
  "gets caught committing bid rigging",
  "gets caught in a corruption scandal",
  "gets caught accepting illegal campaign contributions",
  "gets caught in a lobbying scandal",
  "gets caught in a conflict of interest",
  "gets caught using insider information",
  "gets caught manipulating stock prices",
  "gets caught short selling illegally",
  "gets caught running a crypto scam",
  "gets caught in a pump and dump scheme",
  "gets caught running an illegal gambling operation",
  "gets caught running an illegal casino",
  "gets caught smuggling contraband",
  "gets caught smuggling drugs",
  "gets caught smuggling weapons",
  "gets caught smuggling people",
  "gets caught evading customs",
  "gets caught violating sanctions",
  "gets caught violating export controls",
  "gets caught violating trade embargoes",
  "gets caught violating international law",
  "gets caught committing war crimes",
  "gets caught committing crimes against humanity",
  "gets caught committing genocide",
  "gets caught committing torture",
  "gets caught committing human rights violations",
  "gets caught committing espionage",
  "gets caught committing treason",
  "gets caught committing sedition",
  "gets caught committing terrorism",
  "gets caught committing hate crimes",
  "gets caught committing arson",
  "gets caught committing murder",
  "gets caught committing manslaughter",
  "gets caught committing kidnapping",
  "gets caught in a hostage situation",
];

interface Person {
  name: string;
  type: "titled" | "politician" | "named";
}

function getRandomPerson(): Person {
  const allPeople = [
    ...titledPeople.map(name => ({ name, type: "titled" as const })),
    ...politicians.map(name => ({ name, type: "politician" as const })),
    ...namedPeople.map(name => ({ name, type: "named" as const })),
  ];
  return allPeople[Math.floor(Math.random() * allPeople.length)];
}

function generateBingoPhrase(): string {
  const person = getRandomPerson();
  const action = actions[Math.floor(Math.random() * actions.length)];
  
  // If it's a corporate title, always include a company
  if (person.type === "titled") {
    const company = companies[Math.floor(Math.random() * companies.length)];
    return `${person.name} ${company} ${action}`;
  } 
  // If it's a politician, always include a country
  else if (person.type === "politician") {
    const country = countries[Math.floor(Math.random() * countries.length)];
    return `${person.name} ${country} ${action}`;
  } 
  // If it's a named person, no pairing needed
  else {
    return `${person.name} ${action}`;
  }
}

export function generateBingoPhrases(count: number): string[] {
  const phrases = new Set<string>();
  
  // Generate unique phrases
  while (phrases.size < count) {
    phrases.add(generateBingoPhrase());
  }
  
  return Array.from(phrases);
}